### ISSUE TITLE
Bug in Custom Mode

### ISSUE THREAD

**Issue by StaceyAnnJohnson** [TimeKick/timekick-ios#7]
When setting Custom to every 15 minutes, it keeps saying, "Now reminding you every zero minutes" and then constantly stays the current time.  Also does not work in custom hours.

**Comment by webmd-ios** [comment]
This was broken when we recently removed seconds selection.  This is now fixed.

**Comment by StaceyAnnJohnson** [comment]
Thanks!  Also if it's easy, can we have the default in "time" mode show seconds visually (Not say them), and then you can hide them in settings like you can now?
